experiment_name: sd35m_vae_ft_decoder_only_center_patch_only
seed: 42
runtime:
  gpu_ids:
  - 0
data:
  root: ../data/uwf/multilabel/MedicalCheckup/splitted
  split_filename: default_split.yaml
  train_split: train
  val_split: val
  label_schema_file: configs/labels/proposed_schema.yaml
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
image:
  center_crop_size: 3072
  image_size: 1024
model:
  family: sd35
  variant: medium
  repo_id: stabilityai/stable-diffusion-3.5-medium
  device: cuda
  torch_dtype: bf16
  allow_tf32: true
vae:
  backend: sd35
  use_official: true
  subfolder: vae
  checkpoint: null
  posterior:
    train: mode
    eval: mode
  freeze_patterns:
  - ^encoder\.
  - ^quant_conv\.
  unfreeze_patterns:
  - ^decoder\.
teacher:
  checkpoint: outputs/checkpoints/teacher/teacher_convnextl_proposed/best.pt
  imagenet_pretrained: true
  feature_stage: embedding
train:
  epochs: 10
  batch_size: 2
  num_workers: 4
  lr: 1.0e-05
  weight_decay: 0.0
  grad_accum_steps: 4
  optimizer: adamw
  lr_scheduler: cosine
  save_previews: true
  drop_last: true
loss:
  recon:
    weight: 1.0
    type: l1
    epsilon: 0.001
  kl:
    weight: 1.0e-06
  edge:
    weight: 0.0
    type: sobel_l1
    use_weight_map: false
  weighted_recon:
    weight: 0.0
    type: l1
    epsilon: 0.001
  patch_recon:
    weight: 0.2
    type: charbonnier
    epsilon: 0.001
    crop_ratio: 0.45
    center_x: 0.5
    center_y: 0.5
  weight_map:
    mode: peripheral
    min_weight: 1.0
    max_weight: 3.0
    gamma: 2.0
    inner_radius: 0.35
    apply_retina_mask: true
    retina_threshold: 0.03
  feature:
    weight: 0.0
    type: mse
  logit:
    weight: 0.0
    type: smooth_l1
  lpips:
    weight: 0.0
    net: alex
  noise_feature:
    weight: 0.0
    type: mse
noise_conditioning:
  mode: gaussian
  min_beta: 0.02
  max_beta: 0.25
latent_stats:
  enabled: true
  split: train
  posterior: mode
  max_batches: 128
  update_config: true
  overwrite_saved_dir: false
  also_calibrate_last: true
output:
  root_dir: outputs/checkpoints/vae
wandb:
  enabled: true
  project: uwf-sd35
  name: sd35m_vae_ft_decoder_only_center_patch_only
  mode: online
  log_interval_steps: 10
